#+title: --- Part Two ---

Watching over your shoulder as you work, one of The Historians asks if you
took the effects of resonant harmonics into your calculations.

Whoops!

After updating your model, it turns out that an antinode occurs at any grid
position exactly in line with at least two antennas of the same frequency,
regardless of distance. This means that some of the new antinodes will occur
at the position of each antenna (unless that antenna is the only one of its
frequency).

So, these three T-frequency antennas now create many antinodes:

#+begin_src text
  T....#....
  ...T......
  .T....#...
  .........#
  ..#.......
  ..........
  ...#......
  ..........
  ....#.....
  ..........
#+end_src

In fact, the three T-frequency antennas are all exactly in line with two
antennas, so they are all also antinodes! This brings the total number of
antinodes in the above example to 9.

The original example now has 34 antinodes, including the antinodes that
appear on every antenna:

#+begin_src text
  ##....#....#
  .#.#....0...
  ..#.#0....#.
  ..##...0....
  ....0....#..
  .#...#A....#
  ...#..#.....
  #....#.#....
  ..#.....A...
  ....#....A..
  .#........#.
  ...#......##
#+end_src

Calculate the impact of the signal using this updated model. How many unique
locations within the bounds of the map contain an antinode?
